// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJdC4if018qA1dCZKYu4XxTS5CGGvlOBs',
    appId: '1:393917891206:android:d07afb4c9ab1b43c830707',
    messagingSenderId: '393917891206',
    projectId: 'assinmentluvit',
    databaseURL: 'https://assinmentluvit-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assinmentluvit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMnOE-vAQu0zRWyblChfd2z6VPRxeuI0U',
    appId: '1:393917891206:ios:9e2aac0d63ce6c70830707',
    messagingSenderId: '393917891206',
    projectId: 'assinmentluvit',
    databaseURL: 'https://assinmentluvit-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assinmentluvit.appspot.com',
    iosClientId: '393917891206-dp3fjkc2u7cgs6gofcm7qrj80oictn4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingCardsData',
  );
}
